// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx97iJS1VoaFgZq6pNDqivDom4xApV1MQ',
    appId: '1:653343019542:web:3b445ec10cd3b4999d5b37',
    messagingSenderId: '653343019542',
    projectId: 'newsflight-og',
    authDomain: 'newsflight-og.firebaseapp.com',
    storageBucket: 'newsflight-og.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjMzU6KNABbExCA77lHDLCWmD0bQnMVBY',
    appId: '1:653343019542:android:8bc18454fdf7d0ab9d5b37',
    messagingSenderId: '653343019542',
    projectId: 'newsflight-og',
    storageBucket: 'newsflight-og.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjBPFTRIFWVhDccNsyDSmEvvjRgCVqxLo',
    appId: '1:653343019542:ios:9c22b6d4bcd229039d5b37',
    messagingSenderId: '653343019542',
    projectId: 'newsflight-og',
    storageBucket: 'newsflight-og.appspot.com',
    iosBundleId: 'com.example.nfOg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjBPFTRIFWVhDccNsyDSmEvvjRgCVqxLo',
    appId: '1:653343019542:ios:a2ab6de835928ed49d5b37',
    messagingSenderId: '653343019542',
    projectId: 'newsflight-og',
    storageBucket: 'newsflight-og.appspot.com',
    iosBundleId: 'com.example.nfOg.RunnerTests',
  );
}
